export const CREATE_ROOM_RESULT = "CREATE_ROOM_RESULT";
export const JOIN_ROOM_RESULT = "JOIN_ROOM_RESULT";
export const LOCK_ROOM_RESULT = "LOCK_ROOM_RESULT";
export const LOGIN_RESULT = "LOGIN_RESULT";
export const REGISTER_RESULT = "REGISTER_RESULT";
